spring.application.name=talentbridge-ats


spring.datasource.url=jdbc:mysql://localhost:3306/talentbridge_ats?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=kasundi123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=change-this-to-a-long-random-string-at-least-32-chars
jwt.expiration-ms=86400000
